service: backend

frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-s3-local

custom:
  serverless-offline:
    httpPort: 4000
  s3:
    host: localhost
    port: 8000
    directory: ./mock-s3-data
    buckets:
      - name: ${env:S3_BUCKET_NAME}

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  stage: dev
  environment:
    STAGE: ${self:provider.stage}

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
  authenticateUser:
    handler: src/functions/authenticateUser.authenticateUserHandler
    events:
      - http:
          path: auth/division-pass
          method: post
  startTransaction:
    handler: src/functions/startTransaction.startTransactionHandler
    events:
      - http:
          path: transactions/start
          method: post
  getAvailableLockers:
    handler: src/functions/getAvailableLockers.getAvailableLockersHandler
    events:
      - http:
          path: lockers/available
          method: get
  assignLocker:
    handler: src/functions/assignLocker.assignLockerHandler
    events:
      - http:
          path: lockers/assign
          method: post
  capturePhotos:
    handler: src/functions/capturePhoto.capturePhotoHandler
    events:
      - http:
          path: photos
          method: post
  storeSignature:
    handler: src/functions/storeSignature.storeSignatureHandler
    events:
      - http:
          path: signatures
          method: post
